# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'
schemes:
  - https
info:
  version: 1.0.0
  description: Example Test Flask App
  title: FlaskTestApp # This can't have spaces in it
host: 'localhost:5000'
basePath: /api/1.0.0
x-wso2-security:
  apim:
    x-wso2-scopes:
      - roles: 'admin'
        name: scope-alpha
        key: scope-alpha
        description: Test Scope Alpha

# Is this not configurable from swagger ?
x-prototype_config:
  production_endpoints:
    url: http://localhost:5000

paths:
  /status:
    get:
      x-scope: scope-alpha
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      produces:
        - application/json
      description: |
        gets status of the system
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/StatusMessage'
          examples:
            'application/json':
              message: 'Hello, Status!'
  /alpha:
    get:
      x-scope: scope-alpha
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      description: |
        gets Alpha status of the system
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/StatusMessage'
          examples:
            'application/json':
              message: 'Hello, Status!'
  /beta:
    get:
      x-scope: scope-alpha
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      description: |
        gets Beta status of the system
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/StatusMessage'
          examples:
            'application/json':
              message: 'Hello, Status!'
definitions:
  StatusMessage:
    required:
      - message
    properties:
        message:
          type: string
