create ROLE apiuser with LOGIN ENCRYPTED PASSWORD 'apimanager' CREATEDB;

CREATE DATABASE registry WITH OWNER apiuser ENCODING 'UTF8';
CREATE DATABASE userstore WITH OWNER apiuser ENCODING 'UTF8';
CREATE DATABASE apimgt WITH OWNER apiuser ENCODING 'UTF8';

GRANT ALL PRIVILEGES ON DATABASE apimgt TO apiuser;
GRANT ALL PRIVILEGES ON DATABASE userstore TO apiuser;
GRANT ALL PRIVILEGES ON DATABASE registry TO apiuser;
